### ISSUE TITLE
flowlayers

### ISSUE THREAD

**Issue by mpadge** [ATFutures/upthat#1]
@Robinlovelace I've revisited flow layers, so this should now work (presuming run from in the `flowlayers` directory)
```
devtools::load_all ("../m4ra", export_all = FALSE) # or from whereever you are
devtools::load_all (".", export_all = FALSE)
plot_flows (city = "kathmandu", from = "residential", to = "bus")
```

**Comment by mpadge** [comment]
@Robinlovelace a part of your job will be to try to get multiple layers in with a toggle switch to (de-)select. `mapdeck` won't do that directly, so I'm not sure how to achieve that one? Any ideas?

**Comment by layik** [comment]
I should not feel bad, but I do. Should just use variant of geoplumber apps (ATT). 

mapdeck "should" accept multiple layers, add/remove and should update itself. That is how DeckGL works, unlike Leaflet.

**Comment by layik** [comment]
I just have no idea how David has coded the R package though.

**Comment by Robinlovelace** [comment]
Hey @layik I don't think I have the skills to do rapid prototyping with geoplumber. This is just for getting feedback, not production. Here is the WIP prototype with auto updates within ~1 minute of any commit to this repo.

**Comment by Robinlovelace** [comment]
Happy to use geoplumner, if I can figure out how to set it up to rapid prototype and update every minute or so while the UI is hammered out. @layik here's the link to layer handling in shiny: https://rstudio.github.io/leaflet/showhide.html - which part of that can mapdeck do that leaflet cannot? It's not that I don't want to switch to deck.gl (I do), it about timing.

> part of your job will be to try to get multiple layers in with a toggle switch 

I expect we'll all be working on the UI - try modifying app.R - will be stronger if multiple people are on it.

**Comment by Robinlovelace** [comment]
Closing as non-specific.
