### ISSUE TITLE
serve upthat with sandstorm?

### ISSUE THREAD

**Issue by mpadge** [ATFutures/upthat#11]
@Robinlovelace I just encountered [sandstorm](https://sandstorm.io) - it looks amazing, and is programmed by the guy who made Protocol Buffers (which is how i found out about it). Free to host a local instance, and has a [really different architecture](https://sandstorm.io/how-it-works) that could be really useful for serving upthat. Just a thought?

**Comment by Robinlovelace** [comment]
I remember seeing this a while back. My attitude is 'if it aint broke'... Will send link to instance of upthat that should still be working.

**Comment by mpadge** [comment]
No worries, I'm happy to close - more wanted just to document potential of sandstorm here.
