### ISSUE TITLE
add widget for wait time

### ISSUE THREAD

**Issue by mpadge** [ATFutures/upthat#12]
When I load the data for [New York City](https://github.com/moveability/calibration/issues/7), and click on the menu, it takes a few seconds to load, during which time the main screen looks like it normally does. This has the effect of making it seem - for those brief few seconds - like my selection has done nothing. It'd be good to add a spinny widget that loaded as soon as something is clicked, to give immediate visual feedback that something is happening.

**Comment by Robinlovelace** [comment]
Closing as not in scope for now, can re-open at a later date.
