### ISSUE TITLE
Travis says failing when it's actually succeeding

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#13]
For some reason there are 2 travis CI outputs from this:

![image](https://user-images.githubusercontent.com/1825120/68606146-b4f08d00-04a5-11ea-9a15-868d2d2bcc0a.png)

Is one of them linked to your account @mpadge ? I think we should turn one off.

**Comment by mpadge** [comment]
Not sure about that - travis is passing at present, and there's only one job? Where are the two outputs from?

**Comment by Robinlovelace** [comment]
See commit history. I disabled builds on oneof the Travis pages, seems to have fixed it.
