### ISSUE TITLE
Public instance is down

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#16]
https://atfutures.github.io/uta/

Any ideas @mpadge ? This is the log from `shiny-server`, not sure if this contains the issue:

```
Listening on http://127.0.0.1:37321
Warning in force(expr) :
  strings not representable in native encoding will be translated to UTF-8
Warning in force(expr) :
  input string '�' cannot be translated to UTF-8, is it valid in 'UTF-8' ?
Warning in force(expr) :
  input string '�' cannot be translated to UTF-8, is it valid in 'UTF-8' ?
Warning in force(expr) :
  input string '�' cannot be translated to UTF-8, is it valid in 'UTF-8' ?
No mapdeck token found on system. Trying environment variable MAPBOX
Warning in readRDS(system.file("net-kathmandu.Rds", package = "upthat")) :
  strings not representable in native encoding will be translated to UTF-8
2 files found
Registered S3 method overwritten by 'jsonify':
  method     from    
  print.json jsonlite
2 files found
Warning in readRDS(system.file("net-kathmandu.Rds", package = "upthat")) :
  strings not representable in native encoding will be translated to UTF-8
Warning in readRDS(system.file("net-kathmandu.Rds", package = "upthat")) :
  strings not representable in native encoding will be translated to UTF-8
```

**Comment by mpadge** [comment]
Those warnings should not matter - Kathmandu has original names in Nepalese which are non-UTF-8, but that's okay. The only thing there seems to be a missing mapbox token?

**Comment by Robinlovelace** [comment]
Can you try to reproduce this error @mpadge ? It seems like a bug unrelated to the Mapbox API key to me, which should not cause it to crash in any case. Reprex:

``` r
devtools::install_github("atfutures/upthat")
#> Skipping install of 'upthat' from a github remote, the SHA1 (65f1523a) has not changed since last install.
#>   Use `force = TRUE` to force installation
upthat::runUpthat()
#> Loading required package: shiny
#> 
#> Listening on http://127.0.0.1:4039
#> Error in gzfile(file, "rb") : cannot open the connection
```

![](https://i.imgur.com/5eAwG4Y.png)

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
The reprex works on the previous commit:

``` r
devtools::install_github("atfutures/upthat", ref = "98983a981f0be30e2053b9f76cb32b726ec8c057")
#> Skipping install of 'upthat' from a github remote, the SHA1 (98983a98) has not changed since last install.
#>   Use `force = TRUE` to force installation
upthat::runUpthat()
#> Loading required package: shiny
#> 
#> Listening on http://127.0.0.1:7110
#> 0 files found
#> Registered S3 method overwritten by 'jsonify':
#>   method     from    
#>   print.json jsonlite
```

![](https://i.imgur.com/3Ux87wF.png)

<sup>Created on 2019-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I think this commit is causing the public and local instances to crash: https://github.com/ATFutures/upthat/commit/65f1523ac8c84e991190f261083da7998287b683 - please double check.

**Comment by mpadge** [comment]
@Robinlovelace sorry about that, it was because i changed the default file to Accra, but that's not a `system.file` of the package. I did that because the menu defaults to Accra, which means Kathmandu first loads briefly before switching across to Accra once it's loaded. But that's okay. We can't use Accra as default because it's close to 100 times the (file) size of Kathmandu, but it also doesn't make sense to have K in the menu above A, so good just to leave as is. More important issue is #15, which i've almost got sorted out ...

**Comment by Robinlovelace** [comment]
Thanks for the responsive fix, good Comms.

**Comment by Robinlovelace** [comment]
Just tested the online instance, stoked to see it works again!
