### ISSUE TITLE
Replace 'Recalculate scenario' button with 'Zoom to city extent'

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#32]

**Comment by Robinlovelace** [comment]
A good side effect of fixing this is that it makes #31 a less severe problem.

**Comment by Robinlovelace** [comment]
It's working! I think it still reloads the data which is inefficient. If you know of a way to only update the zoom, PRs are welcome (but not a priority so suggest leaving it).

**Comment by mpadge** [comment]
No, it doesn't reload the data; it just makes a single copy of the focal column. When we start really caring about efficient, we'll just pass column names as variables, and direct `mapdeck` to use `net[[col_name]]`... but also not a priority right now. All good for the moment in current form, I suggest.
