### ISSUE TITLE
Hide UI elements that don't do anything

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/upthat#37]

**Comment by mpadge** [comment]
@Robinlovelace Do you want to take on this one? Should be very straightforward, especially now that new layers are all in, and graph panel is up and running.

**Comment by Robinlovelace** [comment]
True that. MVP that is easy to solve. Can do, was just waiting to see if you could add new columns for scenarios in the flow layers, which is something we said we'd deliver, currently represented in the sliders shown below.


![image](https://user-images.githubusercontent.com/1825120/70342266-96837480-184c-11ea-8e5e-136bc96b45c5.png)

**Comment by mpadge** [comment]
Those come out in the graphs, because the effects of those are visually impossible to distinguish except for overall scale changes. I definitely think we should just remove them from main panel
