### ISSUE TITLE
Expand boundary for Kathmandu network

### ISSUE THREAD

**Issue by mpadge** [ATFutures/upthat#42]
@Robinlovelace FYI the current Kathmandu layers look something like this:
![image](https://user-images.githubusercontent.com/6697851/70341807-0c3f0e80-1854-11ea-8f8e-a1d426fe8068.png)
... where the blob down on the lower left side is because Kathmandu officially stops there, and so the street network does not include Patan across the river. I need to expand it to include Patan as well, which will then enable those flows to disperse across the bridge as they obviously should, and we'll be back to the monocentric pattern we expect there.

**Comment by Robinlovelace** [comment]
Good plan. Please document the code you use to generate the new data.

**Comment by mpadge** [comment]
updated now. You should see something like this:
![image](https://user-images.githubusercontent.com/6697851/70377720-014db200-1918-11ea-96f2-a0053712dd3d.png)

Please close this once you confirm that all looks good on front end.

**Comment by Robinlovelace** [comment]
Can you re-release the data and create a new release each time you push data? 

Just pulled the latest data and it doesn't seem to be updated, as shown below:

```
 piggyback::pb_download()
✔ Setting active project to '/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/atfutures/shinyapps/upthat'
downloading crashes-simulated-accra.Rds ...
  |=======================================================================================================================================================================================| 100%
  |=======================================================================================================================================================================================| 100%
> upthat::runUpthat()
```

Can you try moving your version of the file and trying to reproduce?


![image](https://user-images.githubusercontent.com/1825120/70388898-f9415100-19af-11ea-9014-8b4e31e9bed6.png)

**Comment by Robinlovelace** [comment]
Looking good, deployed.
