### ISSUE TITLE
Ensure pb_download drops data into inst

### ISSUE THREAD

**Issue by mpadge** [ATFutures/upthat#43]
At the moment, data are dumped into main directory, but it would be good if `upthat` only ever looked in `inst` for data. I'm uneasy with the current procedure of just taking first file if copies are both in main dir and inst.

**Comment by Robinlovelace** [comment]
I think it's more time efficient to drop it into the default directory as that is more easy and efficient. Closing for now but happy to re-open if it causes problems. The way I see it is simple: look inside the package's inst folder for demo data and in the root dir for other data files. Makes reproducibility for others who download the repo easier. Happy to re-open and consider alternative ways of managing filepaths but suggest we focus on MVP issues for now.
